CREATE DATABASE HotelManagement
GO

USE HotelManagement
GO

CREATE TABLE Account
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	UserName NVARCHAR(100),
	Password NVARCHAR(100)
)
GO

CREATE TABLE Customer
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(MAX),
	CCCD NVARCHAR(12),
	PhoneNumber INT,
	Nationality NVARCHAR(MAX)
)
GO

CREATE TABLE Staff
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(MAX),
	Sex NVARCHAR(20),
	CCCD NVARCHAR(12),
	PhoneNumber INT,
	Address NVARCHAR(MAX),
	Email NVARCHAR(200),
	Role VARCHAR(20)
)
GO

CREATE TABLE RoomType
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(MAX),
	Price MONEY
)
GO

CREATE TABLE Service
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(MAX),
	Unit NVARCHAR(100),
	Price MONEY,
	ImageFile IMAGE

)
GO

CREATE TABLE Room
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDRoomType INT NOT NULL,
	RoomNumber INT,
	Status NVARCHAR(100) NULL

	FOREIGN KEY (IDRoomType) REFERENCES RoomType(ID),
)
GO

CREATE TABLE ServiceDetail
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDCustomer INT NOT NULL,
	IDRoom INT NOT NULL,
	IDService INT NOT NULL,
	CheckInDate DATETIME,
	CheckOutDate DATETIME

	FOREIGN KEY (IDCustomer) REFERENCES Customer(ID),
	FOREIGN KEY (IDRoom) REFERENCES Room(ID),
	FOREIGN KEY (IDService) REFERENCES Service(ID)
)
GO

CREATE TABLE BuyingDetail
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDService INT NOT NULL,
	IDServieDetail INT NOT NULL,
	Quantity INT,
	OrderPrice MONEY

	FOREIGN KEY (IDService) REFERENCES Service(ID),
	FOREIGN KEY (IDServieDetail) REFERENCES ServiceDetail(ID),
)
GO

CREATE TABLE Bill
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IDServieDetail INT NOT NULL,
	TotalMoney MONEY

	
	FOREIGN KEY (IDServieDetail) REFERENCES ServiceDetail(ID),
)
GO