//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementApp.Model
{
    using HotelManagementApp.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillDetail()
        {
            this.Orders = new HashSet<Order>();
            this.RoomsReservations = new HashSet<RoomsReservation>();
        }
        private int _ID { get; set; }
        private int _IDStaff { get; set; }
        private int _IDCustomer { get; set; }
        private Nullable<decimal> _TotalMoney { get; set; }
        private Nullable<System.DateTime> _BillDate { get; set; }
        private string _Status { get; set; }
        private Nullable<bool> _Deleted { get; set; }

        public int ID { get => _ID; set { _ID = value; OnPropertyChanged(); } }
        public int IDStaff { get => _IDStaff; set { _IDStaff = value; OnPropertyChanged(); } }
        public int IDCustomer { get => _IDCustomer; set { _IDCustomer = value; OnPropertyChanged(); } }
        public Nullable<decimal> TotalMoney { get => _TotalMoney; set { _TotalMoney = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> BillDate { get => _BillDate; set { _BillDate = value; OnPropertyChanged(); } }
        public string Status { get => _Status; set { _Status = value; OnPropertyChanged(); } }
        public Nullable<bool> Deleted { get => _Deleted; set { _Deleted = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomsReservation> RoomsReservations { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
