//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementApp.Model
{
    using HotelManagementApp.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class RoomsReservation : BaseViewModel
    {
        private int _ID { get; set; }
        private Nullable<int> _IDBillDetail { get; set; }
        private Nullable<int> _IDRoom { get; set; }
        private Nullable<System.DateTime> _CheckInTime { get; set; }
        private Nullable<System.DateTime> _CheckOutTime { get; set; }
        private Nullable<bool> _Deleted { get; set; }
        public int ID { get => _ID; set { _ID = value; OnPropertyChanged(); } }
        public Nullable<int> IDBillDetail { get => _IDBillDetail; set { _IDBillDetail = value; OnPropertyChanged(); } }
        public Nullable<int> IDRoom { get => _IDRoom; set { _IDRoom = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> CheckInTime { get => _CheckInTime; set { _CheckInTime = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> CheckOutTime { get => _CheckOutTime; set { _CheckOutTime = value; OnPropertyChanged(); } }
        public Nullable<bool> Deleted { get => _Deleted; set { _Deleted = value; OnPropertyChanged(); } }
        public virtual BillDetail BillDetail { get; set; }
        public virtual Room Room { get; set; }
    }
}
