//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int ID { get; set; }
        public string RoomNum { get; set; }
        public int IDRoomType { get; set; }
        public int IDRoomReservation { get; set; }
        public string Status { get; set; }
        public string ImageData { get; set; }
        public bool Deleted { get; set; }
    
        public virtual RoomsReservation RoomsReservation { get; set; }
        public virtual RoomType RoomType { get; set; }
    }
}
